// Bright Paths Data - CBE Kenya Pathways, Subjects, and Careers

export type Pathway = 'STEM' | 'Social Sciences' | 'Arts & Sports';

export interface Subject {
  code: string;
  name: string;
  pathway: Pathway;
  cluster: string;
}

export interface Career {
  title: string;
  pathway: Pathway;
  description: string;
  growthRate: 'High' | 'Medium' | 'Low';
  salaryRange: string;
  skills: string[];
  education: string;
  industry: string;
  outlook2026: string;
}

export interface QuizQuestion {
  id: number;
  question: string;
  options: {
    text: string;
    pathway: Pathway | null;
  }[];
}

// CBE Subject Clusters and Codes
export const subjects: Subject[] = [
  // STEM Pathway
  { code: 'ST1001', name: 'Mathematics', pathway: 'STEM', cluster: 'Core Sciences' },
  { code: 'ST1002', name: 'Physics', pathway: 'STEM', cluster: 'Core Sciences' },
  { code: 'ST1003', name: 'Chemistry', pathway: 'STEM', cluster: 'Core Sciences' },
  { code: 'ST1004', name: 'Biology', pathway: 'STEM', cluster: 'Core Sciences' },
  { code: 'ST1005', name: 'Computer Science', pathway: 'STEM', cluster: 'Technology' },
  { code: 'ST1006', name: 'Engineering Graphics', pathway: 'STEM', cluster: 'Technology' },
  { code: 'ST1007', name: 'Robotics', pathway: 'STEM', cluster: 'Technology' },
  { code: 'ST1008', name: 'Agriculture', pathway: 'STEM', cluster: 'Applied Sciences' },
  
  // Social Sciences Pathway
  { code: 'SS2001', name: 'History', pathway: 'Social Sciences', cluster: 'Humanities' },
  { code: 'SS2002', name: 'Geography', pathway: 'Social Sciences', cluster: 'Humanities' },
  { code: 'SS2003', name: 'Business Studies', pathway: 'Social Sciences', cluster: 'Commerce' },
  { code: 'SS2004', name: 'Economics', pathway: 'Social Sciences', cluster: 'Commerce' },
  { code: 'SS2005', name: 'Government & Citizenship', pathway: 'Social Sciences', cluster: 'Humanities' },
  { code: 'SS2006', name: 'Religious Studies', pathway: 'Social Sciences', cluster: 'Humanities' },
  { code: 'SS2007', name: 'Languages (Kiswahili)', pathway: 'Social Sciences', cluster: 'Languages' },
  { code: 'SS2008', name: 'Foreign Languages', pathway: 'Social Sciences', cluster: 'Languages' },
  
  // Arts & Sports Pathway
  { code: 'AS3001', name: 'Music', pathway: 'Arts & Sports', cluster: 'Performing Arts' },
  { code: 'AS3002', name: 'Drama/Theatre', pathway: 'Arts & Sports', cluster: 'Performing Arts' },
  { code: 'AS3003', name: 'Visual Arts', pathway: 'Arts & Sports', cluster: 'Visual Arts' },
  { code: 'AS3004', name: 'Film & Media', pathway: 'Arts & Sports', cluster: 'Visual Arts' },
  { code: 'AS3005', name: 'Physical Education', pathway: 'Arts & Sports', cluster: 'Sports Science' },
  { code: 'AS3006', name: 'Sports Management', pathway: 'Arts & Sports', cluster: 'Sports Science' },
  { code: 'AS3007', name: 'Fashion & Design', pathway: 'Arts & Sports', cluster: 'Design' },
  { code: 'AS3008', name: 'Culinary Arts', pathway: 'Arts & Sports', cluster: 'Applied Arts' },
];

// 2026 Kenya Job Market Careers — expanded with richer details
export const careers: Career[] = [
  // ========== STEM Careers (15) ==========
  {
    title: 'Software Developer',
    pathway: 'STEM',
    description: 'Build applications and systems that power Kenya\'s digital economy',
    growthRate: 'High',
    salaryRange: 'KES 80,000 - 350,000/month',
    skills: ['Programming', 'Problem Solving', 'Mathematics'],
    education: 'BSc Computer Science or Software Engineering',
    industry: 'Technology & ICT',
    outlook2026: 'Kenya\'s Silicon Savannah continues rapid expansion with 40%+ growth in tech jobs',
  },
  {
    title: 'Data Analyst',
    pathway: 'STEM',
    description: 'Transform raw data into actionable business insights',
    growthRate: 'High',
    salaryRange: 'KES 70,000 - 200,000/month',
    skills: ['Statistics', 'Python/R', 'Data Visualization'],
    education: 'BSc Statistics, Mathematics, or Data Science',
    industry: 'Finance, Tech & Consulting',
    outlook2026: 'Every major Kenyan company now hiring data teams; demand far exceeds supply',
  },
  {
    title: 'Renewable Energy Engineer',
    pathway: 'STEM',
    description: 'Design solar, wind, and geothermal power solutions for East Africa',
    growthRate: 'High',
    salaryRange: 'KES 100,000 - 300,000/month',
    skills: ['Engineering', 'Physics', 'Project Management'],
    education: 'BSc Electrical or Mechanical Engineering',
    industry: 'Energy & Environment',
    outlook2026: 'Kenya targets 100% green energy by 2030; massive investment in geothermal and solar',
  },
  {
    title: 'Agricultural Technologist',
    pathway: 'STEM',
    description: 'Apply precision farming, drones, and IoT to improve food security',
    growthRate: 'Medium',
    salaryRange: 'KES 50,000 - 150,000/month',
    skills: ['Agriculture', 'Technology', 'Biology'],
    education: 'BSc Agriculture, Agri-Tech, or Horticulture',
    industry: 'Agriculture & Agribusiness',
    outlook2026: 'AgriTech startups growing 25% annually as climate adaptation becomes critical',
  },
  {
    title: 'Biomedical Engineer',
    pathway: 'STEM',
    description: 'Develop medical devices and healthcare technology for African hospitals',
    growthRate: 'High',
    salaryRange: 'KES 90,000 - 250,000/month',
    skills: ['Biology', 'Engineering', 'Chemistry'],
    education: 'BSc Biomedical Engineering or Biomedical Technology',
    industry: 'Healthcare & Medical Technology',
    outlook2026: 'Growing push for locally manufactured medical devices across East Africa',
  },
  {
    title: 'Cybersecurity Specialist',
    pathway: 'STEM',
    description: 'Protect organizations from cyber threats, fraud, and data breaches',
    growthRate: 'High',
    salaryRange: 'KES 100,000 - 400,000/month',
    skills: ['Network Security', 'Programming', 'Risk Analysis'],
    education: 'BSc Computer Science, IT Security, or Cybersecurity',
    industry: 'Finance, Banking & Technology',
    outlook2026: 'Cyberattacks in Kenya up 300% since 2022; massive skills shortage in security',
  },
  {
    title: 'Civil Engineer',
    pathway: 'STEM',
    description: 'Design and oversee construction of roads, buildings, and infrastructure',
    growthRate: 'Medium',
    salaryRange: 'KES 80,000 - 280,000/month',
    skills: ['Mathematics', 'Physics', 'Project Management'],
    education: 'BSc Civil Engineering',
    industry: 'Construction & Infrastructure',
    outlook2026: 'Ongoing road and housing projects across Nairobi, Mombasa, and Konza',
  },
  {
    title: 'Medical Doctor',
    pathway: 'STEM',
    description: 'Diagnose and treat patients in hospitals, clinics, and community health',
    growthRate: 'High',
    salaryRange: 'KES 150,000 - 500,000/month',
    skills: ['Biology', 'Chemistry', 'Patient Care'],
    education: 'MBChB (Bachelor of Medicine and Surgery)',
    industry: 'Healthcare',
    outlook2026: 'Doctor-to-patient ratio still critically low; UHC rollout driving huge demand',
  },
  {
    title: 'Pharmacist',
    pathway: 'STEM',
    description: 'Dispense medications, advise on drug interactions, and support patient care',
    growthRate: 'Medium',
    salaryRange: 'KES 80,000 - 200,000/month',
    skills: ['Chemistry', 'Biology', 'Communication'],
    education: 'BPharm (Bachelor of Pharmacy)',
    industry: 'Healthcare & Pharmaceuticals',
    outlook2026: 'Growing pharmaceutical manufacturing in Kenya; local drug production expanding',
  },
  {
    title: 'Cloud Solutions Architect',
    pathway: 'STEM',
    description: 'Design scalable cloud infrastructure for businesses going digital',
    growthRate: 'High',
    salaryRange: 'KES 120,000 - 450,000/month',
    skills: ['Cloud Platforms', 'Networking', 'System Design'],
    education: 'BSc Computer Science + Cloud Certifications (AWS/Azure)',
    industry: 'Technology & Consulting',
    outlook2026: 'Cloud adoption in Kenya growing 35% year-on-year; AWS and Google expanding presence',
  },
  {
    title: 'Environmental Scientist',
    pathway: 'STEM',
    description: 'Study ecosystems, climate change, and conservation in Kenya\'s diverse biomes',
    growthRate: 'High',
    salaryRange: 'KES 60,000 - 180,000/month',
    skills: ['Biology', 'Research', 'GIS Mapping'],
    education: 'BSc Environmental Science or Conservation Biology',
    industry: 'Environment & Conservation',
    outlook2026: 'Carbon credit markets and conservation funding bringing major investment to Kenya',
  },
  {
    title: 'Mechatronics Technician',
    pathway: 'STEM',
    description: 'Design and maintain automated systems combining mechanics, electronics, and software',
    growthRate: 'Medium',
    salaryRange: 'KES 60,000 - 200,000/month',
    skills: ['Electronics', 'Programming', 'Mechanical Design'],
    education: 'Diploma/BSc Mechatronics or Electrical Engineering',
    industry: 'Manufacturing & Automation',
    outlook2026: 'Kenya\'s manufacturing sector modernizing with Industry 4.0 automation',
  },
  {
    title: 'AI & Machine Learning Engineer',
    pathway: 'STEM',
    description: 'Build intelligent systems that learn from data to solve real-world problems',
    growthRate: 'High',
    salaryRange: 'KES 100,000 - 500,000/month',
    skills: ['Python', 'Mathematics', 'Deep Learning'],
    education: 'BSc/MSc Computer Science, Mathematics, or AI',
    industry: 'Technology & Research',
    outlook2026: 'Africa AI ecosystem exploding; Kenya leading with multiple AI research labs',
  },
  {
    title: 'Veterinarian',
    pathway: 'STEM',
    description: 'Treat animals, manage livestock health, and protect wildlife',
    growthRate: 'Medium',
    salaryRange: 'KES 70,000 - 200,000/month',
    skills: ['Biology', 'Animal Care', 'Surgery'],
    education: 'BVM (Bachelor of Veterinary Medicine)',
    industry: 'Agriculture & Wildlife',
    outlook2026: 'Livestock sector critical to Kenya\'s economy; wildlife conservation growing',
  },
  {
    title: 'Geospatial Analyst',
    pathway: 'STEM',
    description: 'Use satellite data, GIS, and mapping to solve land, urban, and climate challenges',
    growthRate: 'High',
    salaryRange: 'KES 70,000 - 220,000/month',
    skills: ['GIS', 'Remote Sensing', 'Data Analysis'],
    education: 'BSc Geomatics, Geography, or Geospatial Science',
    industry: 'Urban Planning, Agriculture & Environment',
    outlook2026: 'Satellite data and drone mapping transforming agriculture and urban development',
  },

  // ========== Social Sciences Careers (15) ==========
  {
    title: 'Digital Marketing Manager',
    pathway: 'Social Sciences',
    description: 'Lead online marketing strategies across social media, SEO, and paid ads',
    growthRate: 'High',
    salaryRange: 'KES 60,000 - 180,000/month',
    skills: ['Marketing', 'Analytics', 'Communication'],
    education: 'BA Marketing, Communications, or Business',
    industry: 'Marketing & Advertising',
    outlook2026: 'Kenya\'s digital ad spend growing 30% annually; every business needs digital presence',
  },
  {
    title: 'Financial Analyst',
    pathway: 'Social Sciences',
    description: 'Analyze investments, evaluate risks, and guide financial decisions for companies',
    growthRate: 'Medium',
    salaryRange: 'KES 80,000 - 220,000/month',
    skills: ['Economics', 'Mathematics', 'Research'],
    education: 'BCom Finance, Economics, or Actuarial Science',
    industry: 'Banking & Finance',
    outlook2026: 'NSE modernization and fintech growth creating diverse finance career paths',
  },
  {
    title: 'Human Resources Manager',
    pathway: 'Social Sciences',
    description: 'Recruit talent, manage teams, and build organizational culture',
    growthRate: 'Medium',
    salaryRange: 'KES 70,000 - 200,000/month',
    skills: ['Communication', 'Psychology', 'Leadership'],
    education: 'BA Human Resource Management or Business Administration',
    industry: 'Corporate & Professional Services',
    outlook2026: 'Remote work and talent competition driving HR innovation across East Africa',
  },
  {
    title: 'Policy Analyst',
    pathway: 'Social Sciences',
    description: 'Research and shape government policies that drive national development',
    growthRate: 'Medium',
    salaryRange: 'KES 60,000 - 150,000/month',
    skills: ['Research', 'Writing', 'Critical Thinking'],
    education: 'BA Political Science, Public Policy, or Economics',
    industry: 'Government & NGOs',
    outlook2026: 'Devolution creating demand for policy experts at county and national levels',
  },
  {
    title: 'Lawyer / Advocate',
    pathway: 'Social Sciences',
    description: 'Represent clients in court, draft contracts, and advise on legal matters',
    growthRate: 'Medium',
    salaryRange: 'KES 80,000 - 400,000/month',
    skills: ['Legal Knowledge', 'Argumentation', 'Research'],
    education: 'LLB (Bachelor of Laws) + KSL Diploma',
    industry: 'Legal Services',
    outlook2026: 'Specialized areas like cyber law, IP, and environmental law growing fast',
  },
  {
    title: 'Journalist / News Anchor',
    pathway: 'Social Sciences',
    description: 'Investigate stories, report news, and inform the Kenyan public',
    growthRate: 'Medium',
    salaryRange: 'KES 50,000 - 250,000/month',
    skills: ['Writing', 'Communication', 'Research'],
    education: 'BA Journalism, Mass Communication, or Media Studies',
    industry: 'Media & Broadcasting',
    outlook2026: 'Digital media and podcast platforms creating new journalism opportunities',
  },
  {
    title: 'Entrepreneur / Business Owner',
    pathway: 'Social Sciences',
    description: 'Start and grow businesses that create jobs, value, and innovation',
    growthRate: 'High',
    salaryRange: 'KES 50,000 - 1,000,000+/month',
    skills: ['Business Planning', 'Leadership', 'Innovation'],
    education: 'Any degree + business acumen and mentorship',
    industry: 'All Industries',
    outlook2026: 'Kenya ranked #1 in Africa for entrepreneurship; startup funding at record levels',
  },
  {
    title: 'Psychologist / Counselor',
    pathway: 'Social Sciences',
    description: 'Support individuals with mental health, trauma, and personal development',
    growthRate: 'High',
    salaryRange: 'KES 60,000 - 180,000/month',
    skills: ['Psychology', 'Empathy', 'Communication'],
    education: 'BA/BSc Psychology + Counseling certification',
    industry: 'Healthcare & Social Services',
    outlook2026: 'Mental health awareness surging in Kenya; schools and companies hiring counselors',
  },
  {
    title: 'International Relations Officer',
    pathway: 'Social Sciences',
    description: 'Work with foreign governments, embassies, and international organizations',
    growthRate: 'Medium',
    salaryRange: 'KES 100,000 - 350,000/month',
    skills: ['Diplomacy', 'Languages', 'Cultural Awareness'],
    education: 'BA International Relations, Diplomacy, or Political Science',
    industry: 'Government & International Organizations',
    outlook2026: 'Nairobi as UN hub and AfCFTA creating strong demand for diplomats',
  },
  {
    title: 'Real Estate Manager',
    pathway: 'Social Sciences',
    description: 'Manage property investments, developments, and real estate portfolios',
    growthRate: 'High',
    salaryRange: 'KES 70,000 - 300,000/month',
    skills: ['Negotiation', 'Finance', 'Market Analysis'],
    education: 'BA Real Estate, Land Economics, or Business',
    industry: 'Real Estate & Property',
    outlook2026: 'Housing deficit of 2M+ units driving construction and property management boom',
  },
  {
    title: 'Social Worker',
    pathway: 'Social Sciences',
    description: 'Advocate for vulnerable populations including children, refugees, and the elderly',
    growthRate: 'Medium',
    salaryRange: 'KES 40,000 - 120,000/month',
    skills: ['Empathy', 'Case Management', 'Community Engagement'],
    education: 'BA Social Work or Community Development',
    industry: 'NGOs & Government',
    outlook2026: 'Child protection and refugee support programs expanding across the region',
  },
  {
    title: 'Supply Chain Manager',
    pathway: 'Social Sciences',
    description: 'Optimize how goods move from suppliers to customers efficiently',
    growthRate: 'High',
    salaryRange: 'KES 80,000 - 250,000/month',
    skills: ['Logistics', 'Negotiation', 'Data Analysis'],
    education: 'BCom Supply Chain Management or Business Logistics',
    industry: 'Manufacturing, Retail & E-commerce',
    outlook2026: 'E-commerce explosion and regional trade under AfCFTA transforming logistics',
  },
  {
    title: 'Urban Planner',
    pathway: 'Social Sciences',
    description: 'Design sustainable cities, manage land use, and plan transport systems',
    growthRate: 'Medium',
    salaryRange: 'KES 70,000 - 200,000/month',
    skills: ['GIS', 'Community Engagement', 'Policy Analysis'],
    education: 'BA Urban Planning, Geography, or Environmental Planning',
    industry: 'Government & Urban Development',
    outlook2026: 'Rapid urbanization means Kenyan cities need smart planning and transit solutions',
  },
  {
    title: 'Public Health Officer',
    pathway: 'Social Sciences',
    description: 'Design health programs, manage disease outbreaks, and promote community wellness',
    growthRate: 'High',
    salaryRange: 'KES 60,000 - 180,000/month',
    skills: ['Epidemiology', 'Communication', 'Project Management'],
    education: 'BSc Public Health or Environmental Health',
    industry: 'Healthcare & Government',
    outlook2026: 'UHC rollout and pandemic preparedness creating thousands of public health roles',
  },
  {
    title: 'NGO Program Manager',
    pathway: 'Social Sciences',
    description: 'Lead development programs in education, health, environment, and livelihoods',
    growthRate: 'Medium',
    salaryRange: 'KES 80,000 - 300,000/month',
    skills: ['Project Management', 'Grant Writing', 'Monitoring & Evaluation'],
    education: 'BA Development Studies, Social Sciences, or Project Management',
    industry: 'International Development & NGOs',
    outlook2026: 'Kenya hosts 100+ international NGOs; growing demand for local program leaders',
  },

  // ========== Arts & Sports Careers (15) ==========
  {
    title: 'Content Creator / Influencer',
    pathway: 'Arts & Sports',
    description: 'Create engaging content for YouTube, TikTok, Instagram, and digital platforms',
    growthRate: 'High',
    salaryRange: 'KES 30,000 - 500,000/month',
    skills: ['Creativity', 'Video Production', 'Marketing'],
    education: 'Self-taught or Diploma in Media/Communication',
    industry: 'Digital Media & Entertainment',
    outlook2026: 'Kenya\'s creator economy valued at KES 5B+; brand partnerships booming',
  },
  {
    title: 'Professional Athlete',
    pathway: 'Arts & Sports',
    description: 'Compete at national and international levels in athletics, rugby, or football',
    growthRate: 'Medium',
    salaryRange: 'KES 50,000 - 2,000,000/month',
    skills: ['Physical Fitness', 'Discipline', 'Teamwork'],
    education: 'Sports Academy training + competitive experience',
    industry: 'Sports & Athletics',
    outlook2026: 'Kenya\'s athletics dominance continues; new leagues in rugby, football, and basketball',
  },
  {
    title: 'Fashion Designer',
    pathway: 'Arts & Sports',
    description: 'Design clothing and accessories blending African aesthetics with global trends',
    growthRate: 'Medium',
    salaryRange: 'KES 40,000 - 150,000/month',
    skills: ['Design', 'Creativity', 'Business'],
    education: 'Diploma/BA in Fashion Design or Textile Technology',
    industry: 'Fashion & Textiles',
    outlook2026: 'African fashion on global runways; "Buy Kenya Build Kenya" boosting local brands',
  },
  {
    title: 'Film / Video Producer',
    pathway: 'Arts & Sports',
    description: 'Produce films, documentaries, and series for Kenya\'s booming screen industry',
    growthRate: 'High',
    salaryRange: 'KES 50,000 - 300,000/month',
    skills: ['Storytelling', 'Technical Skills', 'Leadership'],
    education: 'BA Film Production, Multimedia, or Communication',
    industry: 'Film & Television',
    outlook2026: 'Netflix, Showmax investing in Kenyan content; local film industry tripling in size',
  },
  {
    title: 'Professional Musician',
    pathway: 'Arts & Sports',
    description: 'Perform, compose, and produce music for live audiences and streaming platforms',
    growthRate: 'High',
    salaryRange: 'KES 30,000 - 1,000,000/month',
    skills: ['Musical Talent', 'Performance', 'Creativity'],
    education: 'Music training, conservatory, or self-taught',
    industry: 'Music & Entertainment',
    outlook2026: 'Streaming royalties growing; Kenyan artists breaking into global markets',
  },
  {
    title: 'Sports Coach / Trainer',
    pathway: 'Arts & Sports',
    description: 'Train athletes and fitness enthusiasts to achieve peak performance',
    growthRate: 'Medium',
    salaryRange: 'KES 40,000 - 200,000/month',
    skills: ['Sports Knowledge', 'Leadership', 'Communication'],
    education: 'BSc Sports Science or Coaching Certification',
    industry: 'Sports & Fitness',
    outlook2026: 'Fitness culture exploding in Kenyan cities; corporate wellness programs expanding',
  },
  {
    title: 'Graphic Designer',
    pathway: 'Arts & Sports',
    description: 'Create visual designs for brands, apps, websites, and marketing campaigns',
    growthRate: 'High',
    salaryRange: 'KES 40,000 - 180,000/month',
    skills: ['Design Software', 'Creativity', 'Visual Communication'],
    education: 'Diploma/BA in Graphic Design or Visual Communication',
    industry: 'Design & Advertising',
    outlook2026: 'Every business needs visual identity; freelance and agency demand both rising',
  },
  {
    title: 'Actor / Actress',
    pathway: 'Arts & Sports',
    description: 'Perform in films, TV shows, commercials, and theatre productions',
    growthRate: 'Medium',
    salaryRange: 'KES 30,000 - 500,000/month',
    skills: ['Acting', 'Expression', 'Voice Control'],
    education: 'Drama training, theatre school, or talent development programs',
    industry: 'Film, TV & Theatre',
    outlook2026: 'Kenyan TV drama and comedy booming; international co-productions increasing',
  },
  {
    title: 'Event Planner',
    pathway: 'Arts & Sports',
    description: 'Organize weddings, concerts, corporate events, and festivals',
    growthRate: 'High',
    salaryRange: 'KES 50,000 - 250,000/month',
    skills: ['Organization', 'Creativity', 'Negotiation'],
    education: 'Diploma in Events Management or Hospitality',
    industry: 'Events & Hospitality',
    outlook2026: 'Kenya\'s events industry recovered strongly post-COVID; MICE tourism growing',
  },
  {
    title: 'Interior Designer',
    pathway: 'Arts & Sports',
    description: 'Design beautiful and functional homes, offices, and commercial spaces',
    growthRate: 'Medium',
    salaryRange: 'KES 50,000 - 200,000/month',
    skills: ['Design', 'Spatial Awareness', 'Client Relations'],
    education: 'BA Interior Design or Architecture',
    industry: 'Design & Real Estate',
    outlook2026: 'Property development boom driving demand for skilled interior designers',
  },
  {
    title: 'Photographer',
    pathway: 'Arts & Sports',
    description: 'Capture moments through wedding, commercial, wildlife, and editorial photography',
    growthRate: 'Medium',
    salaryRange: 'KES 30,000 - 150,000/month',
    skills: ['Photography', 'Editing', 'Creativity'],
    education: 'Photography training or self-taught with portfolio',
    industry: 'Media & Creative Services',
    outlook2026: 'Visual content demand exploding across e-commerce, social media, and tourism',
  },
  {
    title: 'Chef / Culinary Artist',
    pathway: 'Arts & Sports',
    description: 'Create exceptional dishes in restaurants, hotels, and catering businesses',
    growthRate: 'High',
    salaryRange: 'KES 40,000 - 200,000/month',
    skills: ['Cooking', 'Creativity', 'Time Management'],
    education: 'Diploma in Culinary Arts or Hospitality',
    industry: 'Food & Hospitality',
    outlook2026: 'Kenya\'s restaurant scene booming; food tourism and delivery apps driving growth',
  },
  {
    title: 'UX/UI Designer',
    pathway: 'Arts & Sports',
    description: 'Design intuitive digital experiences for apps, websites, and software products',
    growthRate: 'High',
    salaryRange: 'KES 60,000 - 250,000/month',
    skills: ['User Research', 'Figma/Sketch', 'Visual Design'],
    education: 'BA Design, HCI, or self-taught with portfolio',
    industry: 'Technology & Design',
    outlook2026: 'Every tech company needs UX talent; Kenya\'s startup ecosystem driving demand',
  },
  {
    title: 'Animator / Motion Designer',
    pathway: 'Arts & Sports',
    description: 'Create animations for films, ads, games, and educational content',
    growthRate: 'High',
    salaryRange: 'KES 50,000 - 220,000/month',
    skills: ['Animation Software', 'Storytelling', 'Drawing'],
    education: 'Diploma/BA in Animation, Multimedia, or Fine Art',
    industry: 'Media & Entertainment',
    outlook2026: 'African animation studios gaining global recognition; Netflix and Disney investing',
  },
  {
    title: 'Sports Physiotherapist',
    pathway: 'Arts & Sports',
    description: 'Rehabilitate athletes and help people recover from injuries through therapy',
    growthRate: 'Medium',
    salaryRange: 'KES 60,000 - 180,000/month',
    skills: ['Anatomy', 'Rehabilitation', 'Patient Care'],
    education: 'BSc Physiotherapy or Sports Rehabilitation',
    industry: 'Healthcare & Sports Medicine',
    outlook2026: 'Growing sports industry and fitness culture increasing demand for sports medicine',
  },

  // ========== NEW CAREERS (20 additional) ==========

  // --- STEM (7 more) ---
  {
    title: 'Blockchain Developer',
    pathway: 'STEM',
    description: 'Build decentralized applications, smart contracts, and fintech solutions on blockchain platforms',
    growthRate: 'High',
    salaryRange: 'KES 120,000 - 500,000/month',
    skills: ['Solidity', 'Cryptography', 'Smart Contracts'],
    education: 'BSc Computer Science or Software Engineering',
    industry: 'Fintech & Cryptocurrency',
    outlook2026: 'M-Pesa integration with blockchain; Kenya leading African crypto adoption',
  },
  {
    title: 'Drone Operations Engineer',
    pathway: 'STEM',
    description: 'Design, pilot, and maintain drones for agriculture, delivery, and surveying',
    growthRate: 'High',
    salaryRange: 'KES 70,000 - 220,000/month',
    skills: ['Aeronautics', 'Remote Sensing', 'GIS'],
    education: 'BSc Aerospace Engineering, Geomatics, or KCAA Drone Licence',
    industry: 'Agriculture, Logistics & Surveying',
    outlook2026: 'KCAA drone regulations opening commercial applications across multiple sectors',
  },
  {
    title: 'Biostatistician',
    pathway: 'STEM',
    description: 'Apply statistical methods to medical research, clinical trials, and public health data',
    growthRate: 'High',
    salaryRange: 'KES 90,000 - 280,000/month',
    skills: ['Statistics', 'R/SAS', 'Epidemiology'],
    education: 'MSc Biostatistics or Statistics',
    industry: 'Healthcare & Research',
    outlook2026: 'KEMRI and international health orgs expanding clinical research capacity in East Africa',
  },
  {
    title: 'Telecommunications Engineer',
    pathway: 'STEM',
    description: 'Design and maintain mobile networks, 5G infrastructure, and fibre-optic systems',
    growthRate: 'Medium',
    salaryRange: 'KES 80,000 - 250,000/month',
    skills: ['Networking', 'RF Engineering', 'Signal Processing'],
    education: 'BSc Electrical & Telecommunications Engineering',
    industry: 'Telecommunications',
    outlook2026: '5G rollout across Kenyan cities driving massive infrastructure investment',
  },
  {
    title: 'Robotics Engineer',
    pathway: 'STEM',
    description: 'Design and program robots for manufacturing, agriculture, and service industries',
    growthRate: 'High',
    salaryRange: 'KES 100,000 - 350,000/month',
    skills: ['Programming', 'Mechanical Design', 'AI'],
    education: 'BSc Mechatronics, Robotics, or Computer Engineering',
    industry: 'Manufacturing & Technology',
    outlook2026: 'Kenya investing in industrial automation; robotics labs expanding at top universities',
  },
  {
    title: 'Food Scientist',
    pathway: 'STEM',
    description: 'Develop and test food products for safety, nutrition, and quality standards',
    growthRate: 'Medium',
    salaryRange: 'KES 60,000 - 180,000/month',
    skills: ['Chemistry', 'Microbiology', 'Quality Control'],
    education: 'BSc Food Science & Technology',
    industry: 'Food Processing & FMCG',
    outlook2026: 'KEBS standards tightening; value-added food exports to EAC growing rapidly',
  },
  {
    title: 'Petroleum Geologist',
    pathway: 'STEM',
    description: 'Explore and assess oil, gas, and mineral resources using geological data',
    growthRate: 'Medium',
    salaryRange: 'KES 120,000 - 400,000/month',
    skills: ['Geology', 'Seismic Analysis', 'GIS'],
    education: 'BSc Geology or Earth Sciences',
    industry: 'Oil, Gas & Mining',
    outlook2026: 'Turkana oil project and mineral exploration in northern Kenya creating specialised roles',
  },

  // --- Social Sciences (7 more) ---
  {
    title: 'Tax Consultant',
    pathway: 'Social Sciences',
    description: 'Advise individuals and businesses on tax compliance, planning, and KRA obligations',
    growthRate: 'High',
    salaryRange: 'KES 80,000 - 300,000/month',
    skills: ['Taxation', 'Accounting', 'Regulatory Knowledge'],
    education: 'BCom Accounting or CPA-K qualification',
    industry: 'Finance & Consulting',
    outlook2026: 'KRA digital tax reforms creating huge demand for qualified tax professionals',
  },
  {
    title: 'Customs & Trade Officer',
    pathway: 'Social Sciences',
    description: 'Facilitate cross-border trade, manage tariffs, and ensure regulatory compliance',
    growthRate: 'Medium',
    salaryRange: 'KES 70,000 - 200,000/month',
    skills: ['Trade Law', 'Logistics', 'Negotiation'],
    education: 'BA International Trade, Economics, or Customs Administration',
    industry: 'Government & International Trade',
    outlook2026: 'AfCFTA implementation boosting intra-African trade; port modernization at Mombasa',
  },
  {
    title: 'Education Technologist',
    pathway: 'Social Sciences',
    description: 'Design digital learning platforms, e-learning content, and edtech solutions',
    growthRate: 'High',
    salaryRange: 'KES 60,000 - 200,000/month',
    skills: ['Instructional Design', 'EdTech Tools', 'Curriculum Development'],
    education: 'BA Education Technology, ICT in Education, or Instructional Design',
    industry: 'Education & Technology',
    outlook2026: 'CBC digital integration and edtech startups transforming Kenyan classrooms',
  },
  {
    title: 'Insurance Underwriter',
    pathway: 'Social Sciences',
    description: 'Assess risk and determine insurance premiums for clients and businesses',
    growthRate: 'Medium',
    salaryRange: 'KES 70,000 - 220,000/month',
    skills: ['Risk Assessment', 'Mathematics', 'Decision Making'],
    education: 'BCom Insurance, Actuarial Science, or ACII qualification',
    industry: 'Insurance & Risk Management',
    outlook2026: 'Insurance penetration in Kenya still low; massive growth potential as awareness rises',
  },
  {
    title: 'Conflict Resolution Specialist',
    pathway: 'Social Sciences',
    description: 'Mediate disputes, facilitate peace-building, and manage community conflicts',
    growthRate: 'Medium',
    salaryRange: 'KES 60,000 - 180,000/month',
    skills: ['Mediation', 'Negotiation', 'Cultural Sensitivity'],
    education: 'BA Peace & Conflict Studies, Law, or International Relations',
    industry: 'NGOs, Government & International Organizations',
    outlook2026: 'Regional security challenges and devolution increasing demand for trained mediators',
  },
  {
    title: 'Sustainability Consultant',
    pathway: 'Social Sciences',
    description: 'Help organizations adopt sustainable practices, ESG reporting, and green strategies',
    growthRate: 'High',
    salaryRange: 'KES 80,000 - 250,000/month',
    skills: ['Environmental Policy', 'Data Analysis', 'Strategy'],
    education: 'BA Environmental Studies, Business, or Development Studies',
    industry: 'Consulting & Environment',
    outlook2026: 'Carbon credit markets and ESG mandates making sustainability roles essential',
  },
  {
    title: 'Market Research Analyst',
    pathway: 'Social Sciences',
    description: 'Study consumer behavior, market trends, and competitor strategies to guide business decisions',
    growthRate: 'High',
    salaryRange: 'KES 60,000 - 200,000/month',
    skills: ['Research', 'Statistics', 'Communication'],
    education: 'BA Marketing, Statistics, or Social Sciences',
    industry: 'Market Research & FMCG',
    outlook2026: 'Data-driven decision making becoming standard; FMCG and tech firms scaling research teams',
  },

  // --- Arts & Sports (6 more) ---
  {
    title: 'Game Developer',
    pathway: 'Arts & Sports',
    description: 'Design and build video games and interactive experiences for mobile and console platforms',
    growthRate: 'High',
    salaryRange: 'KES 60,000 - 250,000/month',
    skills: ['Unity/Unreal', 'Programming', '3D Modelling'],
    education: 'BSc Computer Science, Game Development, or self-taught with portfolio',
    industry: 'Gaming & Entertainment',
    outlook2026: 'Africa\'s gaming market growing 12% yearly; Kenyan studios gaining international attention',
  },
  {
    title: 'Dance Choreographer',
    pathway: 'Arts & Sports',
    description: 'Create original dance routines for music videos, live shows, and cultural performances',
    growthRate: 'Medium',
    salaryRange: 'KES 30,000 - 200,000/month',
    skills: ['Dance', 'Creativity', 'Fitness'],
    education: 'Dance academy training or performing arts diploma',
    industry: 'Entertainment & Performing Arts',
    outlook2026: 'Viral dance challenges and Afrobeats culture fueling professional dance careers',
  },
  {
    title: 'Sound Engineer',
    pathway: 'Arts & Sports',
    description: 'Record, mix, and master audio for music, film, radio, and live events',
    growthRate: 'High',
    salaryRange: 'KES 50,000 - 200,000/month',
    skills: ['Audio Production', 'DAW Software', 'Acoustics'],
    education: 'Diploma in Sound Engineering or Music Production',
    industry: 'Music, Film & Broadcasting',
    outlook2026: 'Kenya\'s music and podcast industries creating steady demand for audio professionals',
  },
  {
    title: 'Sports Journalist',
    pathway: 'Arts & Sports',
    description: 'Report on sporting events, interview athletes, and create sports content',
    growthRate: 'Medium',
    salaryRange: 'KES 40,000 - 180,000/month',
    skills: ['Writing', 'Sports Knowledge', 'Broadcasting'],
    education: 'BA Journalism or Mass Communication + Sports expertise',
    industry: 'Media & Sports',
    outlook2026: 'KPL, rugby sevens, and athletics creating year-round sports media demand',
  },
  {
    title: 'Tattoo & Body Artist',
    pathway: 'Arts & Sports',
    description: 'Create custom tattoo designs, body art, and cosmetic enhancements',
    growthRate: 'Medium',
    salaryRange: 'KES 30,000 - 150,000/month',
    skills: ['Drawing', 'Hygiene Standards', 'Client Relations'],
    education: 'Apprenticeship or art school training',
    industry: 'Personal Services & Creative Arts',
    outlook2026: 'Tattoo culture growing rapidly in urban Kenya; stigma fading among younger demographics',
  },
  {
    title: 'Esports Manager',
    pathway: 'Arts & Sports',
    description: 'Manage competitive gaming teams, organize tournaments, and develop esports brands',
    growthRate: 'High',
    salaryRange: 'KES 50,000 - 200,000/month',
    skills: ['Gaming Strategy', 'Team Management', 'Marketing'],
    education: 'BA Sports Management, Marketing, or self-taught with gaming experience',
    industry: 'Esports & Gaming',
    outlook2026: 'African esports scene expanding; Kenya hosting major regional gaming tournaments',
  },
];

// Full question pool for randomization - indirect scenario-based questions
export const allQuizQuestions: QuizQuestion[] = [
  {
    id: 1,
    question: 'You find an old, mysterious box in your grandparent\'s attic. You would first:',
    options: [
      { text: 'Examine its mechanism and figure out how to open it', pathway: 'STEM' },
      { text: 'Research its history and what it might have been used for', pathway: 'Social Sciences' },
      { text: 'Appreciate its craftsmanship and imagine its story', pathway: 'Arts & Sports' },
    ],
  },
  {
    id: 2,
    question: 'During a power outage at night, you would most likely:',
    options: [
      { text: 'Check the fuse box and troubleshoot the issue', pathway: 'STEM' },
      { text: 'Call neighbors to see if they\'re affected and coordinate', pathway: 'Social Sciences' },
      { text: 'Light candles and enjoy the change of atmosphere', pathway: 'Arts & Sports' },
    ],
  },
  {
    id: 3,
    question: 'A friend asks for advice on choosing a new phone. You focus on:',
    options: [
      { text: 'Comparing specifications, battery life, and processing power', pathway: 'STEM' },
      { text: 'Discussing value for money and what their friends use', pathway: 'Social Sciences' },
      { text: 'Looking at the design, camera quality for photos, and colors', pathway: 'Arts & Sports' },
    ],
  },
  {
    id: 4,
    question: 'You notice a bird building a nest outside your window. You think about:',
    options: [
      { text: 'The engineering precision and physics of the nest structure', pathway: 'STEM' },
      { text: 'How bird behavior reflects survival and community instincts', pathway: 'Social Sciences' },
      { text: 'The beauty of nature and wanting to sketch or photograph it', pathway: 'Arts & Sports' },
    ],
  },
  {
    id: 5,
    question: 'Your family is planning to renovate the kitchen. You get excited about:',
    options: [
      { text: 'The plumbing, electrical work, and how appliances will be installed', pathway: 'STEM' },
      { text: 'The budget, getting quotes, and coordinating with contractors', pathway: 'Social Sciences' },
      { text: 'Choosing colors, tiles, and making the space look beautiful', pathway: 'Arts & Sports' },
    ],
  },
  {
    id: 6,
    question: 'You\'re stuck in traffic. To pass time, you:',
    options: [
      { text: 'Wonder about traffic flow patterns and how signals could be optimized', pathway: 'STEM' },
      { text: 'Listen to a podcast about current events or business', pathway: 'Social Sciences' },
      { text: 'Enjoy your music playlist or daydream about creative ideas', pathway: 'Arts & Sports' },
    ],
  },
  {
    id: 7,
    question: 'At a family gathering, you naturally end up:',
    options: [
      { text: 'Fixing someone\'s phone or explaining how something works', pathway: 'STEM' },
      { text: 'Catching up on family news and mediating discussions', pathway: 'Social Sciences' },
      { text: 'Entertaining the kids or taking photos of everyone', pathway: 'Arts & Sports' },
    ],
  },
  {
    id: 8,
    question: 'You discover a shortcut to school/work. You appreciate it because:',
    options: [
      { text: 'You calculated it saves exactly 7 minutes each way', pathway: 'STEM' },
      { text: 'You can share it with others and help them save time too', pathway: 'Social Sciences' },
      { text: 'The route passes by a nice park with beautiful scenery', pathway: 'Arts & Sports' },
    ],
  },
  {
    id: 9,
    question: 'When cooking a meal, you tend to:',
    options: [
      { text: 'Follow the recipe precisely, measuring everything exactly', pathway: 'STEM' },
      { text: 'Think about who will eat it and what they prefer', pathway: 'Social Sciences' },
      { text: 'Experiment with flavors and focus on presentation', pathway: 'Arts & Sports' },
    ],
  },
  {
    id: 10,
    question: 'A younger cousin asks why the sky is blue. You:',
    options: [
      { text: 'Explain light scattering and wavelengths in simple terms', pathway: 'STEM' },
      { text: 'Ask them what color they think it should be and explore ideas', pathway: 'Social Sciences' },
      { text: 'Point out how many shades of blue there are at different times', pathway: 'Arts & Sports' },
    ],
  },
  {
    id: 11,
    question: 'You\'re helping organize a birthday party. You volunteer to handle:',
    options: [
      { text: 'Setting up the sound system and lighting', pathway: 'STEM' },
      { text: 'Managing the guest list and sending invitations', pathway: 'Social Sciences' },
      { text: 'Decorating the venue and choosing the playlist', pathway: 'Arts & Sports' },
    ],
  },
  {
    id: 12,
    question: 'While waiting at a bus stop, you observe:',
    options: [
      { text: 'How the bus schedule could be more efficient', pathway: 'STEM' },
      { text: 'The different types of people and wonder about their stories', pathway: 'Social Sciences' },
      { text: 'Interesting street art or take photos of the surroundings', pathway: 'Arts & Sports' },
    ],
  },
  {
    id: 13,
    question: 'Your phone battery is draining fast. Your first reaction is to:',
    options: [
      { text: 'Check which apps are using power and optimize settings', pathway: 'STEM' },
      { text: 'Ask friends if they\'ve had similar issues and what they did', pathway: 'Social Sciences' },
      { text: 'Not worry much - you can survive without it for a while', pathway: 'Arts & Sports' },
    ],
  },
  {
    id: 14,
    question: 'When packing for a trip, you prioritize:',
    options: [
      { text: 'A checklist and making sure all essentials are covered', pathway: 'STEM' },
      { text: 'Gifts for people you\'ll visit and travel documents', pathway: 'Social Sciences' },
      { text: 'Outfits that look good and your camera or sketchbook', pathway: 'Arts & Sports' },
    ],
  },
  {
    id: 15,
    question: 'A classmate copies your work. You feel most bothered by:',
    options: [
      { text: 'The fact that they didn\'t try to understand the solution themselves', pathway: 'STEM' },
      { text: 'The unfairness of the situation and what it means for trust', pathway: 'Social Sciences' },
      { text: 'That they didn\'t put in their own creative effort', pathway: 'Arts & Sports' },
    ],
  },
  {
    id: 16,
    question: 'You receive money as a gift. Your first thought is:',
    options: [
      { text: 'Save it or invest it in something useful like a course or gadget', pathway: 'STEM' },
      { text: 'Think about who gave it and how to thank them properly', pathway: 'Social Sciences' },
      { text: 'Buy something fun - clothes, art supplies, or event tickets', pathway: 'Arts & Sports' },
    ],
  },
  {
    id: 17,
    question: 'During a long matatu/bus journey, you:',
    options: [
      { text: 'Read articles or watch educational videos', pathway: 'STEM' },
      { text: 'Chat with fellow passengers or observe conversations', pathway: 'Social Sciences' },
      { text: 'Listen to music, doodle, or take photos of the scenery', pathway: 'Arts & Sports' },
    ],
  },
  {
    id: 18,
    question: 'Your neighbor\'s dog won\'t stop barking. You think:',
    options: [
      { text: 'There must be a logical trigger - maybe a sound or animal nearby', pathway: 'STEM' },
      { text: 'I should talk to the neighbor about it politely', pathway: 'Social Sciences' },
      { text: 'Poor dog might be stressed - I wonder if playing music would help', pathway: 'Arts & Sports' },
    ],
  },
  {
    id: 19,
    question: 'When trying a new restaurant, you pay attention to:',
    options: [
      { text: 'Whether the food is well-prepared and the portions are fair', pathway: 'STEM' },
      { text: 'The service, atmosphere, and whether you\'d recommend it', pathway: 'Social Sciences' },
      { text: 'The presentation of dishes and the décor of the place', pathway: 'Arts & Sports' },
    ],
  },
  {
    id: 20,
    question: 'You overhear someone sharing wrong information. You:',
    options: [
      { text: 'Feel compelled to correct them with accurate facts', pathway: 'STEM' },
      { text: 'Consider whether it\'s your place to say something and how', pathway: 'Social Sciences' },
      { text: 'Let it go unless it\'s really important - not your problem', pathway: 'Arts & Sports' },
    ],
  },
  {
    id: 21,
    question: 'Your favorite part of a movie is usually:',
    options: [
      { text: 'The plot logic, realistic technology, or clever twists', pathway: 'STEM' },
      { text: 'The character relationships and emotional depth', pathway: 'Social Sciences' },
      { text: 'The cinematography, soundtrack, and visual style', pathway: 'Arts & Sports' },
    ],
  },
  {
    id: 22,
    question: 'When you see a rainbow, you think:',
    options: [
      { text: 'About light refraction and the physics creating the colors', pathway: 'STEM' },
      { text: 'It\'s a nice moment to share - you\'d tell someone about it', pathway: 'Social Sciences' },
      { text: 'It\'s beautiful and you want to take a picture or paint it', pathway: 'Arts & Sports' },
    ],
  },
  {
    id: 23,
    question: 'A friend is upset about failing an exam. You:',
    options: [
      { text: 'Offer to help them study more effectively next time', pathway: 'STEM' },
      { text: 'Listen to them vent and offer emotional support', pathway: 'Social Sciences' },
      { text: 'Suggest doing something fun to take their mind off it', pathway: 'Arts & Sports' },
    ],
  },
  {
    id: 24,
    question: 'At a market, you\'re drawn to:',
    options: [
      { text: 'Gadgets, electronics, or useful household tools', pathway: 'STEM' },
      { text: 'Negotiating good deals and chatting with vendors', pathway: 'Social Sciences' },
      { text: 'Handmade crafts, colorful fabrics, and unique items', pathway: 'Arts & Sports' },
    ],
  },
  {
    id: 25,
    question: 'When assembling furniture from a box, you:',
    options: [
      { text: 'Read the manual carefully and follow steps precisely', pathway: 'STEM' },
      { text: 'Call a friend to help and make it a social activity', pathway: 'Social Sciences' },
      { text: 'Figure it out by looking at the picture - manuals are boring', pathway: 'Arts & Sports' },
    ],
  },
  {
    id: 26,
    question: 'You notice a leak in the roof during rain. You first:',
    options: [
      { text: 'Investigate where the water is coming from and assess damage', pathway: 'STEM' },
      { text: 'Alert family members and discuss who to call for repairs', pathway: 'Social Sciences' },
      { text: 'Grab a bucket and towels to manage the immediate situation', pathway: 'Arts & Sports' },
    ],
  },
  {
    id: 27,
    question: 'When choosing what to wear, you consider:',
    options: [
      { text: 'What\'s practical for the weather and activities planned', pathway: 'STEM' },
      { text: 'What impression you want to make on people you\'ll meet', pathway: 'Social Sciences' },
      { text: 'What looks good together and expresses your style', pathway: 'Arts & Sports' },
    ],
  },
  {
    id: 28,
    question: 'Your internet suddenly stops working. You:',
    options: [
      { text: 'Check the router, run diagnostics, and troubleshoot', pathway: 'STEM' },
      { text: 'Call the service provider and calmly explain the issue', pathway: 'Social Sciences' },
      { text: 'Use the time to do something offline like reading or exercise', pathway: 'Arts & Sports' },
    ],
  },
  {
    id: 29,
    question: 'When planning your day, you prefer:',
    options: [
      { text: 'A detailed schedule with times for each activity', pathway: 'STEM' },
      { text: 'Knowing who you\'ll see and what conversations to have', pathway: 'Social Sciences' },
      { text: 'Keeping it flexible for spontaneous moments', pathway: 'Arts & Sports' },
    ],
  },
  {
    id: 30,
    question: 'You find a wallet on the street. You:',
    options: [
      { text: 'Look for ID to figure out how to return it efficiently', pathway: 'STEM' },
      { text: 'Think about how worried the owner must be and try to find them', pathway: 'Social Sciences' },
      { text: 'Hand it to nearby security or a shop - someone will sort it out', pathway: 'Arts & Sports' },
    ],
  },
  {
    id: 31,
    question: 'When someone shares good news, you:',
    options: [
      { text: 'Ask detailed questions about how it happened', pathway: 'STEM' },
      { text: 'Congratulate them warmly and celebrate with them', pathway: 'Social Sciences' },
      { text: 'Suggest a way to mark the occasion - dinner, photos, etc.', pathway: 'Arts & Sports' },
    ],
  },
  {
    id: 32,
    question: 'You\'re bored at home with nothing to do. You:',
    options: [
      { text: 'Watch documentaries or tinker with something around the house', pathway: 'STEM' },
      { text: 'Call a friend or scroll through social media to see what\'s happening', pathway: 'Social Sciences' },
      { text: 'Put on music, draw, exercise, or start a creative project', pathway: 'Arts & Sports' },
    ],
  },
  {
    id: 33,
    question: 'When you can\'t sleep at night, you typically:',
    options: [
      { text: 'Read articles or think about problems you want to solve', pathway: 'STEM' },
      { text: 'Reflect on conversations or plan what to say to someone', pathway: 'Social Sciences' },
      { text: 'Listen to calming music or imagine creative scenarios', pathway: 'Arts & Sports' },
    ],
  },
  {
    id: 34,
    question: 'A teacher/boss asks for a volunteer. You step up if it involves:',
    options: [
      { text: 'Setting up equipment or solving a technical problem', pathway: 'STEM' },
      { text: 'Representing the group or speaking on behalf of others', pathway: 'Social Sciences' },
      { text: 'Performing, demonstrating, or showcasing something creative', pathway: 'Arts & Sports' },
    ],
  },
  {
    id: 35,
    question: 'At the end of a long day, you feel most satisfied if you:',
    options: [
      { text: 'Accomplished something tangible - fixed, built, or learned something', pathway: 'STEM' },
      { text: 'Had meaningful conversations and helped someone', pathway: 'Social Sciences' },
      { text: 'Did something you enjoyed - exercise, music, or creativity', pathway: 'Arts & Sports' },
    ],
  },
];

// Function to get randomized questions for each session
export function getRandomQuizQuestions(count: number = 15): QuizQuestion[] {
  const shuffled = [...allQuizQuestions].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count).map((q, index) => ({ ...q, id: index + 1 }));
}

// Legacy export for compatibility
export const quizQuestions = allQuizQuestions.slice(0, 10);

// Job market trends 2026 weights — BALANCED across all pathways
// Equal weights ensure the quiz (70%) is the primary differentiator,
// not a baked-in bias toward any single pathway
export const jobMarketWeights: Record<Pathway, number> = {
  'STEM': 1.15,
  'Social Sciences': 1.15,
  'Arts & Sports': 1.15,
};

// Get randomized career recommendations for a pathway
export function getRandomCareers(pathway: Pathway, count: number = 5): Career[] {
  const pathwayCareers = careers.filter(c => c.pathway === pathway);
  const shuffled = [...pathwayCareers].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}
